### ISSUE TITLE
Redirect Uri doesn't exist.

### ISSUE THREAD

**Issue by farishkash** [sgoswa01/jammming#1]
https://github.com/sgoswa01/jammming/blob/02e60cec99df7c37c7a571ae924e391eaeb34a84/src/util/Spotify.js#L5

I am in the process of reviewing and debugging this program as there are some code issues and your project doesn't exist on surge.  If I change it to localhost it still will not work because spotify doesn't allow localhost to have access due to app permissions. Ths makes this difficult to review. 
 I did find one major issue without needing the project to run but I am not sure if I can give this a full review as a result of this.  I will try my best.  Screenshot below.

![my_site](https://user-images.githubusercontent.com/5844161/37264513-eccd3e60-256a-11e8-9b9a-55005e6f65f0.png)

**Comment by sgoswa01** [comment]
Fixed issues that happened while deploying
