### ISSUE TITLE
Term is not part of the state.

### ISSUE THREAD

**Issue by farishkash** [sgoswa01/jammming#2]
https://github.com/sgoswa01/jammming/blob/02e60cec99df7c37c7a571ae924e391eaeb34a84/src/components/SearchBar/SearchBar.js#L13

Nowhere did you add the value of term to the state.  So this will come up as null since it has never been initialized.

![jammming](https://user-images.githubusercontent.com/5844161/37264707-35f05ff4-256c-11e8-9328-51246ee45fdc.png)

```
In your SearchBar.js constructor, you would write the code like this.

class SearchBar extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      term: ''
    };


    this.search = this.search.bind(this);
    this.handleTermChange = this.handleTermChange.bind(this);
  }
```

**Comment by sgoswa01** [comment]
Added this.state = {term: '' }; to the constructor of SearchBar
