### ISSUE TITLE
No access token provided

### ISSUE THREAD

**Issue by farishkash** [sgoswa01/jammming#3]
https://github.com/sgoswa01/jammming/blob/02e60cec99df7c37c7a571ae924e391eaeb34a84/src/util/Spotify.js#L27-L30

In order for this to work properly, you need to provide an accessToken when sending a fetch request.

In order this to happen you need to call the function that you wrote earlier to get the accessToken.

```
search(term) {
    const accessToken = Spotify.getAccessToken();
    const searchUrl = `https://api.spotify.com/v1/search?type=track&q=${term}`

    return fetch(searchUrl, {
      headers: {Authorization: `Bearer ${accessToken}`}
    }).then(response => response.json()).then(jsonResponse => {
```

**Comment by sgoswa01** [comment]
Fixed the getAccessToken method and added const accessToken = Spotify.getAccessToken(); to the search method
