### ISSUE TITLE
Accesstoken similar issue.

### ISSUE THREAD

**Issue by farishkash** [sgoswa01/jammming#4]
https://github.com/sgoswa01/jammming/blob/02e60cec99df7c37c7a571ae924e391eaeb34a84/src/util/Spotify.js#L55

Two issues here, first like the previous issue you need to call the function to get the accessToken. 

Second, you already declare this here.

https://github.com/sgoswa01/jammming/blob/02e60cec99df7c37c7a571ae924e391eaeb34a84/src/util/Spotify.js#L3

There is no reason to use const and try to declare it again, this will reset the global variable and cause problems through the project with this data not being accessible or rewritable.

**Comment by sgoswa01** [comment]
Removed const accessToken = accessToken
